### PR TITLE
VPS: Installation of GitLab

### PR DESCRIPTION
**Pull request by TriggeredLegend**
- I've written a detailed guide on how to set up GitLab on your server from ZAP-Hosting, in line with my approved suggestion #1311

### CODE REVIEW

**Comment by ThatGuyJacobee** [comment]
Hey there @TriggeredLegend!

Thank you for your PR, the installation process was clear and well made, good job overall. I made some general content adjustments to try to make it a bit more clear. For example, I moved Step 3 to be outside of the <Tabs> to prevent repeating it 3 times, instead just replacing it with 2 commands, one for Ubuntu/Debian and another for OpenSUSE. 👍

Also, remember to include the end `:::` when creating an admonition. For example, to create a tip you should do:
```
:::tip
Did you know that this is cool!
::: <--- Remember the end tag :)
```

Please let me know if you prefer to receive your reward payout through PayPal, or as ZAP Coins (credits) towards your ZAP-Hosting account (which comes with a 30% extra bonus :)?

Once you provide me with this info and my colleague does some final checks, I'll be able to finalise this Contribution and provide you with the payout. 🙂

Many thanks! 💚

**Comment by TriggeredLegend** [comment]
Hey @ThatGuyJacobee !!

- Thank you for your reply. I really appreciate your feedback once again!!!

- Regarding the payment reward, I prefer to receive it via **PayPal**. Thank you! I will wait for the final confirmation.

**Review by ThatGuyJacobee — APPROVED** [review]
g2g

**Comment by ThatGuyJacobee** [comment]
Hey there @TriggeredLegend! We accept your final submission for this contribution and thank you for your interest and participation in the Contribution Program.

We have sent a PayPal payout confirmation ticket to your provided ZAP-Hosting Account. You must now send us an invoice using the PayPal Invoice Creator, including the ticket # number of the payout confirmation in the description. Please read our [guide](https://zap-hosting.com/guides/docs/contribution-rewards/#paypal) for more information.

Once you have sent your invoice, it may take up to a few days to be processed. Thank you for contributing and we hope to see you contribute more in the future! 💚

**Pull request merged**
