### PR TITLE
New guide for linking Top Level Domain with Cloudflare.

### PR DESCRIPTION
**Pull request by Thetntteam**
#1224 - Register domain with cloudflare issue

I have created a guide that explains how to link up a Top Level Domain with Cloudflare. Cloudflare is a very popular DNS management service and website owners often link up their domain with Cloudflare as a first step.  By providing easy to follow step-by-step instructions, this guide aims to walk new and experienced website owners through linking Cloudflare nameservers with their Top Level Domain.

### CODE REVIEW

**Comment by ThatGuyJacobee** [comment]
Heya @Thetntteam! I apologise for the longer than expected wait.

Generally, the content was well-written and with appropriate information. Thank you for including screenshots for both languages too. :)

Could you let me know, do you wish to payout through PayPal, or as credits to your ZAP-Hosting account (comes with a 30% bonus). My colleague will do a final review shortly, and once you provide me with your choice of payout we will be able to perform your reward payout. 

Many thanks!

**Comment by Thetntteam** [comment]
Zap-Hosting creditOn May 2, 2024, at 9:09 PM, Jacob ***@***.***> wrote:﻿
Heya @Thetntteam! I apologise for the longer than expected wait.
Generally, the content was well-written and with appropriate information. Thank you for including screenshots for both languages too. :)
Could you let me know, do you wish to payout through PayPal, or as credits to your ZAP-Hosting account (comes with a 30% bonus). My colleague will do a final review shortly, and once you provide me with your choice of payout we will be able to perform your reward payout.
Many thanks!

**Comment by Thetntteam** [comment]
sorry it looks terrible cause i replied theough email. Zap Hosting credit please

**Comment by Thetntteam** [comment]
When can I expect the reward payout/this being added to the website?

**Comment by Thetntteam** [comment]
Hey @ThatGuyJacobee , I'm new to this and am not sure how I claim the reward. Will it be automatically added to my account or is there something else I need to do? Thanks for your time.

**Comment by ThatGuyJacobee** [comment]
Heya @Thetntteam! Apologies for the late reply, it was a busy end of the week and a bank holiday today.

Thank you for your contribution, I have added your reward payout to your ZAP-Hosting account with the 30% bonus being included due to picking this method. You don't have to do anything else. 🙂

Once again, thank you for contributing and we hope to see you contribute more in the future! 💚

**Pull request merged**
