### PR TITLE
Webspace: Migrating Your WordPress Site to Zap Hosting

### PR DESCRIPTION
**Pull request by TriggeredLegend**
I've written a detailed guide on migrating your WordPress site to Zap Hosting, in line with my approved suggestion #1305.

### CODE REVIEW

**Comment by ThatGuyJacobee** [comment]
Hey there @TriggeredLegend!

Thank you for your PR, the content overall explained the WP migration process pretty well. I had to make some content adjustments, especially with the format to make it more chronological and easier to digest. 👍

Please let me know if you prefer to receive your reward payout through PayPal, or as ZAP Coins (credits) towards your ZAP-Hosting account (which comes with a 30% extra bonus :)?

Once you provide me with this info and my colleague does some final checks, I'll be able to finalise this Contribution and provide you with the payout. 🙂

Many thanks! 💚

**Review by ThatGuyJacobee — APPROVED** [review]
Ready to be merged. May need a quick look at the German translation.

**Comment by TriggeredLegend** [comment]
Hey @ThatGuyJacobee  !!

Thank you for your reply. I appreciate your feedback and the changes made. They have helped me understand the style to follow for future submissions, and I will make sure to adhere to it more carefully.

Regarding the payment reward, I prefer to receive it via **PayPal**. Thank you! I will wait for the final confirmation.

**Comment by TriggeredLegend** [comment]
Hey @fgalz ,
- I've added the German screenshots below the English ones. Kindly check.

Best regards,
Triggered Legend

**Comment by ThatGuyJacobee** [comment]
Hey there @TriggeredLegend! We accept your final submission for this contribution and thank you for your interest and participation in the Contribution Program.

We have sent a PayPal payout confirmation ticket to your provided ZAP-Hosting Account. You must now send us an invoice using the PayPal Invoice Creator, including the ticket # number of the payout confirmation in the description. Please read our [guide](https://zap-hosting.com/guides/docs/contribution-rewards/#paypal) for more information.

Once you have sent your invoice, it may take up to a few days to be processed. Thank you for contributing and we hope to see you contribute more in the future! 💚

**Review by ThatGuyJacobee — APPROVED** [review]
Ready for merge!

**Pull request merged**
