### PR TITLE
Create dedicated-pterodactyl.md

### PR DESCRIPTION
**Pull request by nicolasbaud**
The PR for the issues #1210

### CODE REVIEW

**Comment by ThatGuyJacobee** [comment]
Hi there @nicolasbaud!

We have finished reviewing your PR and had to make quite a significant amount of adjustments as it was written in a very monotonous way and didn't fully follow our guidelines. We also noted that the content was similar to the official Pterodactyl guide.

Your contribution is now completed, please let me know what payout method you wish to use, PayPal or credits to your ZAP-Hosting account (comes with 30% bonus). Once you get back to me, I'll be able to evaluate the final reward and we will be able to payout and publish the guide. 🙂

Many thanks!

**Comment by nicolasbaud** [comment]
Hello @ThatGuyJacobee,

Credit on my ZAP-Hosting account please.

**Comment by ThatGuyJacobee** [comment]
Hey there! @nicolasbaud 

We accept your final submission for this contribution and thank you for your interest and participation in your Contribution Program. I have credited your ZAP-Hosting Account with the final contribution reward. Since you picked ZAP Coins as your payout method, you received an extra 30% on the base payout that we evaluated.

Once again, thank you for contributing and we hope to see you contribute more in the future!

**Review by ThatGuyJacobee — APPROVED** [review]
LGTM

**Pull request merged**
