### PR TITLE
Corrections & improvements

### PR DESCRIPTION
**Pull request by OfficialSkypo**
- Various brand name/trademark corrections
- ZAP-Hosting GmbH & Co. KG to ZAP-Hosting GmbH correction
- Discount code C2A tweaks

🤓

### CODE REVIEW

**Review by ThatGuyJacobee — APPROVED** [review]
Changes look good :)

**Comment by ThatGuyJacobee** [comment]
I think Paul has a valid point @OfficialSkypo, might be best to keep it as it was for the extra context it provides for readers :)

What do you think?

**Comment by OfficialSkypo** [comment]
> A quick question: What is the idea behind changing the voucher heading's wording?
> 
> My idea when I labelled it as a hosting voucher is that people might visit the website based on a Google search for an explanation or a guide related to CloudFlare for instance. The heading currently gives them context so they know what kind of voucher this is and implicitly what we're offering. In my mind, there is a good chance they skipped the note about the products at the top of the post (there might not even be any associated products), but it is quite likely they read the heading in the voucher box within the content. Without this heading, they are kind of left in the dark if they are not familiar with us as a company or our services.

The reason for this was to simply make it uniform to the general words & descriptions we use on other pages / types of content.
But very fair point that it makes it more logical to understand for prospects. Feel free to revert that part of the change.

**Comment by ThatGuyJacobee** [comment]
Superseded by the above ^

**Pull request closed without merging**
