### PR TITLE
Added Python runtime install guide.

### PR DESCRIPTION
**Pull request by itscc8**
This PR adds the python runtime install guide mentioned in #1119

### CODE REVIEW

**Comment by ThatGuyJacobee** [comment]
Hi there @itscc8,

Thanks for submitting your final Pull Request! Could you please let me know if you wish to payout using PayPal, or as credits towards your ZAP-Hosting account (which comes with a 30% bonus :). Once you get back to me, we can finalise the payout and publish the guide!

Many thanks! 🙂

**Comment by itscc8** [comment]
Hey @ThatGuyJacobee I'd like to try out the paypal payout

**Comment by ThatGuyJacobee** [comment]
Hey @itscc8. We accept your final submission for this contribution and thank you for your interest and participation in your Contribution Program.

We have sent a PayPal payout confirmation ticket to your provided ZAP-Hosting Account. You must now send us an invoice using the [PayPal Invoice Creator](https://www.paypal.com/invoice/create?fromWidget=newuser), with the following contents:
- Fill in our company information as the recipient: `ZAP-Hosting GmbH & Co. KG, Hafenweg 8, 48155 Münster, Deutschland`
- Description must include both your ZAP ID and the ticket ID for your payout confirmation ticket, as following: `Contribution Program Payout: Ticket #[yourticket_id], [your_zapid]`
- Invoice must be sent to: `m.kluck@zap-hosting.com`

If you have any questions, please let me know. Many thanks!

**Comment by itscc8** [comment]
^ Started writing the other guides and accidently pushed changes to master. Since I don't want to modify this PR I will make a separate branch.

**Comment by ThatGuyJacobee** [comment]
Hey there @itscc8! We thank you for your interest and participation in your Contribution Program. 🙂

We have credited ZAP Coins to your ZAP-Hosting account as you requested, and I have cancelled the PayPal payout. Your new guide will be published soon! Once again, thank you for contributing and we hope to see you contribute more in the future! 💚

**Pull request merged**
